
<?php if (isset($session['email'])) : ?>
    <?=  $session['email'] ?>
    <form action="/session" method="post">
        <input type="hidden" name="_METHOD" value="DELETE">
        <input type="submit" value="Sign Out">
    </form>
<?php else: ?>
    <form action="/session" method="post">
        <input type="text" name="user[email]" value="">
        <input type="submit" value="Sign In">
    </form>
<?php endif; ?>

