<form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
        <label>
            Поменять имя пользователя
            <input type="text" name="user[name]" value="<?= htmlspecialchars($postUser['name'])  ?? '' ?>">
        </label>
        <?php if (isset($errors['name'])): ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Update">
</form>
