<form action="/form" method="post">
    <div>
        <label>
            Имя
            <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name']) ?>">
        </label>
        <?php if (isset($errors['name'])): ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Email
            <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
        </label>
        <?php if (isset($errors['email'])): ?>
            <div><?= $errors['email'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Id
            <input type="number" name="user[id]" value="<?= htmlspecialchars($user['id']) ?>">
        </label>
        <?php if (isset($errors['id'])): ?>
            <div><?= $errors['id'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Save">
</form>